"""add timezone to User v2

Revision ID: f8e27766f79c
Revises: 
Create Date: 2025-07-20 17:28:36.418098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e27766f79c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'debts', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key(None, 'repeat_operations', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'repeat_operations', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'repeat_operations', 'limits', ['limit_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'targets', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'limits', ['limit_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'])
    op.add_column('users', sa.Column('timezone', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'targets', type_='foreignkey')
    op.drop_constraint(None, 'repeat_operations', type_='foreignkey')
    op.drop_constraint(None, 'repeat_operations', type_='foreignkey')
    op.drop_constraint(None, 'repeat_operations', type_='foreignkey')
    op.drop_constraint(None, 'debts', type_='foreignkey')
    # ### end Alembic commands ###
